https:
  listener:
    host: "0.0.0.0"
    port: "8081"
  
kafka:
  server: "pkc-ep9mm.us-east-2.aws.confluent.cloud:9092" #UPDATE
# Kafka authentication details: username and password- Add below 
  username: "" #UPDATE
  password: "" #UPDATE
# Kafka Remote Server Truststore and its password 
  tls:
    password: "" #UPDATE
    path: "${app.home}/ssl/confluent-use2-truststore.jks" #UPDATE
  bufferSize: "10"
  bufferSizeUnit: "MB"
  maximumRequestSize: "10"
  topic: 
    name: "test-topic-five-partitions" #UPDATE
    partition:
      size: "10"